name = "hono-workers-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "hono-db"
database_id = "local"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "local"
