name = "hono-workers-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "hono-db"
database_id = "169a55a1-d89e-4ca4-b56a-21dd80148a4b"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "bc9f8bbeba1f4a77b256e2aa323f1386"

[triggers]
crons = ["0 */6 * * *"]
